version: "3.8"

services:
  app:
    build: .
    container_name: waitlist-manager-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/local
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: waitlist-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=local

volumes:
  mongo-data:
